### ISSUE TITLE
Please deploy TLS

### ISSUE THREAD

**Issue by strugee** [StudentRND/s5#2]
I don't want to send my password and sensitive information over HTTP. Please deploy HTTPS on s5.studentrnd.org.

**Comment by tylermenezes** [comment]
HTTPS is already supported on s5.

**Comment by strugee** [comment]
In that case, can you issue HTTP redirects to the TLSified version?

**Comment by strugee** [comment]
@tylermenezes did you see the above comment? I still don't see redirects.
